format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character
"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red)"

[directory]
truncate_to_repo = false

